### PR TITLE
Add OS Updater

### PR DESCRIPTION
**Pull request by Teko012**
It implements #127 halfway, it can't update the supervisor at the moment. The original project is archived, so I modernized it as much as I could, but ideally, it definitely needs more love, and the supervisor logic should be implemented as well.

### CODE REVIEW

**Comment by Teko012** [comment]
I managed to test this, it works well.

**Comment by ketilmo** [comment]
One more excellent addition; kudos and thanks, @Teko012! Is there an easy way to disable this? Some stations running in remote locations should probably only be updated manually.

**Comment by Teko012** [comment]
@ketilmo Of course, it has the same disable mechanism implemented like the other services: https://github.com/ketilmo/balena-ads-b/pull/138/files#diff-c939a28b1f9d62cf9982e75a40042f60f6e78b02292336bc3247b084da6cda3aR6-R11

**Comment by ketilmo** [comment]
@Teko012,

That's great! I'm just wondering if we should make it opt-in for now to avoid breaking the setup for people with remote boxes (in the event of a bad update). What do you think? Any thoughts from you on this, @shawaj?

**Comment by Teko012** [comment]
@ketilmo We could make it like that, although people should probably look regardless before they update, as we are not versioning these releases. Feel free to update the commit with the logic that you think would makes sense :)

**Comment by Teko012** [comment]
@ketilmo What should we do about this?

**Comment by ketilmo** [comment]
@Teko012 I will come back to you on this one. (Can you contact me directly via DM, email or channel of your choice? I have something I need to discuss with you.)

**Comment by shawaj** [comment]
> @Teko012,
> 
> That's great! I'm just wondering if we should make it opt-in for now to avoid breaking the setup for people with remote boxes (in the event of a bad update). What do you think? Any thoughts from you on this, @shawaj?

Yes I kind of agree that it should be disabled by default and only enabled by specifically enabling. To avoid unintended balenaOS updates bricking something. 

Having said that, I personally don't see the point in the functionality at all as you can already do supervisor and balenaOS updates directly from the balenaCloud dashboard on demand. But maybe that's just me (and I note this also comes from a user request)

**Comment by Teko012** [comment]
@ketilmo (Sent you a DM on Instagram)

@shawaj Yeah, but thats manual, some people want to have it automatically. Although this only fulfills half and only implements OS updates, and its missing the supervisor updates. Do you think we should introduce a new enable variable, or should we just set the disable by default, and people can overwrite it?

**Comment by Teko012** [comment]
@shawaj Update the MR. Can you check?

**Comment by Teko012** [comment]
@shawaj Seems like something is wrong with the pipeline implementation as well 🤔

**Comment by shawaj** [comment]
> @shawaj Seems like something is wrong with the pipeline implementation as well 🤔

It seems to be that the token for login is missing. But it's not. Must be because the PR comes from your personal repo not this one directly... There must be some peculiarity in his GitHub deals with these tokens.

**Comment by Teko012** [comment]
> > @shawaj Seems like something is wrong with the pipeline implementation as well 🤔
> 
> It seems to be that the token for login is missing. But it's not. Must be because the PR comes from your personal repo not this one directly... There must be some peculiarity in his GitHub deals with these tokens.

I think it can be set to only run after approval, and make it accessible for PRs too after that. But I think we can't change that, only @ketilmo

**Comment by shawaj** [comment]
Works perfectly so merging :-)

With no env variable the container auto-exits. With `ENABLED_SERVICES` set to `autohupr` the container loads and gives following output (my OS is up to date already)

image

**Pull request merged**
