### PR TITLE
Update balena dependencies

### PR DESCRIPTION
**Pull request by Teko012**
It updates the balena dependencies and modernizes the repo a little bit.

### CODE REVIEW

**Comment by Teko012** [comment]
@ketilmo If you can test this change, that would be greatly appreciated. I can't currently test the kiosk change.

**Comment by ketilmo** [comment]
Thanks for your suggested improvements, this looks great! I'm currently on vacation, but will test the changes when I get back.

**Comment by Teko012** [comment]
@ketilmo When do you think you will be able to review these? :)

**Comment by ketilmo** [comment]
Thanks for the reminder, @Teko012, and for your patience! I’ve been travelling for the past four weeks but am on my way home now. I will start testing the proposed changes asap. :)

**Comment by ketilmo** [comment]
Thank you so much for these significant improvements, @Teko012! They all look good to me. Well done!

**Pull request merged**
