### PR TITLE
feat: add wingbits service

### PR DESCRIPTION
**Pull request by shawaj**
@ketilmo I have added a definition here for wingbits service.

I'm also planning to do one for DeFli.

I just wanted to open this draft PR to start the discussion about contributing.

I will of course add documentation but just wanted to see if there was anything else you would want me to do to get this merged other than adding docs and squashing commits?

### CODE REVIEW

**Comment by ketilmo** [comment]
Hi @shawaj!

Thank you so much for your pull request! It's appreciated. This is my first time hearing of this service, which sounds very interesting. I will sign up and take your pull request for a test run. Is it correctly understood that I must buy a vector to start sharing?

**Comment by shawaj** [comment]
no you don't need to buy a hex for the device to show online and contribute data, but you do need to buy a hex for you to earn any tokens in the future.

i don't think the token earning stuff is live yet though

**Comment by ketilmo** [comment]
I have just attempted to deploy the service to one of my stations. While it starts running successfully, it hangs midway through startup, (possibly due to being unable to connect to 127.0.0.1 at port 30006, which it appears to be able to do soon after). I have a slightly modified dockerfile in this particular test environment and have not been able to debug this yet. This is a heads-up in case something obvious could be sorted easily.

```
wingbits  Settings verified, proceeding with startup.
 wingbits   
 wingbits  [readsb-wingbits]     invoked by: /usr/bin/feed-wingbits --net --net-only --debug=n --quiet --net-connector localhost,30006,json_out --write-json /run/wingbits-feed --net-beast-reduce-interval 0.5 --net-heartbeat 60 --net-ro-size 1280 --net-ro-interval 0.2 --net-ro-port 0 --net-sbs-port 0 --net-bi-port 30154 --net-bo-port 0 --net-ri-port 0 --net-connector dump1090-fa,30005,beast_in
 wingbits  [readsb-wingbits]     Tue Nov 21 21:22:43 2023 UTC  readsb starting up.
 wingbits  [readsb-wingbits]     readsb version: 3.14.1600 wiedehopf git: f535e51 (committed: Tue Mar 14 13:17:07 2023 0100)
 wingbits  [readsb-wingbits]     30154: Beast TCP input port           
 wingbits  2023-11-21T21:22:43.138492Z  INFO vector::app: Log level is enabled. level="vector=info,codec=info,vrl=info,file_source=info,tower_limit=info,rdkafka=info,buffers=info,lapin=info,kube=info"
 wingbits  2023-11-21T21:22:43.144412Z  INFO vector::config::watcher: Creating configuration file watcher.
 wingbits  2023-11-21T21:22:43.146011Z  INFO vector::config::watcher: Watching configuration files.
 wingbits  2023-11-21T21:22:43.146792Z  INFO vector::app: Loading configs. paths=["/etc/vector/vector.yaml"]
 wingbits  [readsb-wingbits]     Position json output: Attempting connection to localhost port 30006 ...
 wingbits  [readsb-wingbits]     Beast TCP input: Attempting connection to dump1090-fa port 30005 ...
 wingbits  [readsb-wingbits]     Beast TCP input: Connection established: dump1090-fa (172.17.0.13) port 30005
 wingbits  [readsb-wingbits]     Position json output: Connection to localhost (127.0.0.1) port 30006 failed: 111 (Connection refused)
 wingbits  [readsb-wingbits]     Position json output: Attempting connection to localhost port 30006 ...
 wingbits  [readsb-wingbits]     Position json output: Connection to localhost (::1) port 30006 failed: Transport endpoint is not connected
 wingbits  2023-11-21T21:22:43.457141Z  INFO vector: Vector has started. debug="false" version="0.34.1" arch="aarch64" revision="86f1c22 2023-11-16 14:59:10.486846964"
 wingbits  2023-11-21T21:22:43.457235Z  INFO vector::app: API is disabled, enable by setting `api.enabled` to `true` and use commands like `vector top`.
 wingbits  2023-11-21T21:22:43.444912Z  INFO vector::topology::running: Running healthchecks.
 wingbits  2023-11-21T21:22:43.457800Z  INFO source{component_kind="source" component_id=readsb component_type=socket}: vector::sources::util::net::tcp: Listening. addr=127.0.0.1:30006
 wingbits  2023-11-21T21:22:43.663100Z  INFO vector::topology::builder: Healthcheck passed.
 wingbits  [readsb-wingbits]     Position json output: Attempting connection to localhost port 30006 ...
 wingbits  [readsb-wingbits]     Position json output: Connection established: localhost (127.0.0.1) port 30006
```

**Comment by ketilmo** [comment]
Sorry, my mistake. I mixed up the Hex and ID when populating the `WINGBITS_DEVICE_ID`. When correcting that mistake, the feeding started working instantly. Looks good so far (on RPi 4). Will continue testing on an RPi 3. :)

**Comment by ketilmo** [comment]
It's running beautifully on RPi3, too. Well done! I have looked through your pull request, and it looks great. I appreciate the way you have been following the conventions and setup. It makes the repo coherent and easier to maintain. Thanks a lot! 👏🏻

If you could also add a section to the Readme – a new part 9 maybe, moving the sections after that downwards – it would be great!

**Comment by shawaj** [comment]
Cool, will add some docs tomorrow 👌

**Comment by shawaj** [comment]
@ketilmo ok a few fixes added and README updated now. let me know if that looks ok?

**Comment by ketilmo** [comment]
Wow, that was fast! And I really appreciate your attention to detail both in the code and in the docs. Thanks again for your contribution to the project. This is good to go! ✈️

**Comment by ketilmo** [comment]
Implements #91

**Comment by shawaj** [comment]
> Wow, that was fast! 

I got into it last night. I even surprised myself 😂

> And I really appreciate your attention to detail both in the code and in the docs. Thanks again for your contribution to the project. This is good to go! ✈️

I know first hand how annoying it is when people submit a good PR but with a bunch of mistakes and issues. Still great to get contributions but a little bit annoying when you have to spend hours tidying them up etc 😭

The joys of open source stuff I guess 😉

Will try and do a few more PRs for DeFli and some of the adsb exchange clones in the coming weeks 👍

**Comment by ketilmo** [comment]
Thank you, @shawaj! Much appreciated! 🙏🏻

**Pull request merged**
