### PR TITLE
wingbits: bump to latest version

### PR DESCRIPTION
**Pull request by shawaj**
Bump to latest config version

Closes: #105

### CODE REVIEW

**Comment by Teko012** [comment]
@shawaj Do we need the vector.yaml? It's commented out in the docker file, I think the line and the yaml could be dropped.

**Comment by shawaj** [comment]
> @shawaj Do we need the vector.yaml? It's commented out in the docker file, I think the line and the yaml could be dropped.

Yeah AFAICT we don't need them at all here. @ketilmo - were these left just left in before during testing? Wasn't sure if there was a particular reason or not.

**Comment by ketilmo** [comment]
@shawaj @Teko012 

Yes, this file and the reference to it can be removed. In the first versions of the Wingbits service, the file was stored locally. But after the update this spring, the file is downloaded automatically during build time.

**Comment by shawaj** [comment]
> @shawaj @Teko012
> 
> Yes, this file and the reference to it can be removed. In the first versions of the Wingbits service, the file was stored locally. But after the update this spring, the file is downloaded automatically during build time.

Perfect will update and rebase

**Comment by ketilmo** [comment]
Looks good to me, @shawaj! Thanks for sharing your improvements.

**Comment by shawaj** [comment]
oh i was going to rebase but you beat me to it :-P

No probs @ketilmo 👍

**Pull request merged**
