### PR TITLE
Add renovate config

### PR DESCRIPTION
**Pull request by Teko012**
Add renovate config

### CODE REVIEW

**Comment by ketilmo** [comment]
Thanks @Teko012, looks good! Merging.

**Comment by ketilmo** [comment]
@Teko012 Let me know if/when I should start merging Renovate pull requests. :)

**Comment by Teko012** [comment]
@ketilmo I think the one that's open can be start merging/testing, or reviewing. Some of them might need a bit of research

**Comment by ketilmo** [comment]
Ok, thanks!

**Pull request merged**
