### PR TITLE
add notes about RPi4 and using a display

### PR DESCRIPTION
**Pull request by xginn8**
Signed-off-by: Matthew McGinn <matthew@balena.io>

### CODE REVIEW

**Comment by vimondketil** [comment]
This is awesome, @xginn8! Thanks for contributing!

Just to understand the functionality fully –

- For the code to build on Balena without errors, the repository would always need to be cloned with the `git clone --recursive {{repository URL}}`, right? (Due to how Balena resolves sub-repos).
- The LAUNCH_URL variable: Can it be passed a hostname as well as an IP? If yes, I guess setting LAUNCH_URL to `dump1090-fa:8754` would then expose the FlightAware tracking page.

**Comment by ketilmo** [comment]
This is awesome, @xginn8! Thanks for contributing!

Just to understand the functionality fully –

- For the code to build on Balena without errors, the repository would always need to be cloned with the `git clone --recursive {{repository URL}}`, right? (Due to how Balena resolves sub-repos).
- The LAUNCH_URL variable: Can it be passed a hostname as well as an IP? If yes, I guess setting LAUNCH_URL to `dump1090-fa:8754` would then expose the FlightAware tracking page.

**Comment by ketilmo** [comment]
One more question, @xginn8: Is the `wifi-connect`-feature enabled by default?

**Comment by xginn8** [comment]
> This is awesome, @xginn8! Thanks for contributing!
> 
> Just to understand the functionality fully –
> 
>     * For the code to build on Balena without errors, the repository would always need to be cloned with the `git clone --recursive {{repository URL}}`, right? (Due to how Balena resolves sub-repos).
Yep, I can include it directly if you prefer but figured I was ~the only one using this with a monitor so I opted to submodule it.

> 
>     * The LAUNCH_URL variable: Can it be passed a hostname as well as an IP? If yes, I guess setting LAUNCH_URL to `dump1090-fa:8754` would then expose the FlightAware tracking page.

That's correct, since the `kiosk` service is not using host networking any URL (or local named service) can be passed there. I can make a note of that, since it's helpful.

**Comment by xginn8** [comment]
> One more question, @xginn8: Is the `wifi-connect`-feature enabled by default?

It isn't, but it certainly can be! If `wifi-connect` detects an active connection profile, it does nothing anyway.

**Comment by ketilmo** [comment]
> That's correct, since the kiosk service is not using host networking any URL (or local named service) can be passed there. I can make a note of that, since it's helpful.

Sounds great, thanks!

> It isn't, but it certainly can be! If wifi-connect detects an active connection profile, it does nothing anyway.

I think that sounds like a good option. As long as it's not overriding any previously set connections profiles (including cabled ethernet), it sounds fine to enable it by default. Is the wifi-connect settings persisted after reboots?

**Comment by xginn8** [comment]
@ketilmo PTAL, I cleaned up your suggestions and added a `Deploy with balena` button to make deploying a little easier (see https://www.balena.io/docs/learn/deploy/deploy-with-balena-button/ for more information)

**Comment by ketilmo** [comment]
@xginn8 This is great! Thanks for your efforts, it's highly appreciated. I'll go ahead and merge in your suggestions now.

**Pull request merged**
