### PR TITLE
Increase the allowed usbfs buffer size

### PR DESCRIPTION
**Pull request by Teko012**
I ran into this problem from time to time, I'm not exactly sure this will solve it, but this is what the output of the error suggest.

### CODE REVIEW

**Comment by Teko012** [comment]
@ketilmo As you have more knowledge maybe about it, can you check if this works as expected?

**Comment by ketilmo** [comment]
Hi @Teko012! Thanks for your suggestion, it looks good to me. I have just one question: Should the same snippet be applied to dump978 as well?

**Comment by Teko012** [comment]
@ketilmo To be honest, I'm not sure, but it could make sense potentially. If you want, I can add it. This error is kind of hard to reproduce on my side, it randomly pops up after a restart, and I had to restart a few times to fix it again. It would be also good if you could test it for dump1090 as well, I want to make sure we are not breaking something.

**Comment by ketilmo** [comment]
@Teko012 Understand! dump978 uses SoapySDR, so it might not be necessary to add it to that service. Let's keep it as it is for now. The PR looks good to me, so I'm merging it. Thanks for your great work!

**Pull request merged**
