### PR TITLE
Updates to adsbexchange integration

### PR DESCRIPTION
**Pull request by wiedehopf**
PLEASE TEST BEFORE MERGING :)

In regards to: https://github.com/ketilmo/balena-ads-b/issues/39

Thought i might just change what i have in mind, easier than ask you to do it all.
I'm not super familiar with how you build so i leave the testing up to you.

### CODE REVIEW

**Comment by ketilmo** [comment]
Looks excellent, @wiedehopf! I have added a few modules and made som slight changes (see commit) to make it work. If you are happy, we can merge this in.

For the create-sitename-script: Is it correctly understood that you don't want it to add random numbers to the site name anymore? 

Please feel free to come with more suggestions as you see fit, and give us a shout when you want the versions to be bumped.

**Comment by wiedehopf** [comment]
The random numbers are no longer necessary as the server now instead of rejecting the connection will just append numers to your username if there are duplicate usernames for whatever reason.

This seems good, once you have merged this i can get rid of all the unnecessary history in that adsbecxhange readsb repo ... make it a fork of my repo.
The commit id won't change so that's all good.

This should be pretty much the same as the adsbexchange feed script install.
Go ahead and merge it once you've confirmed it's working :)


Only thing i can think of is that your image is missing a nice interface ;P
It should be straight forward to add tar1090 using /run/adsbexchange as a data source if you're interested.
https://github.com/wiedehopf/tar1090#tar1090
The components you need are the html directory, http configuration pointing at /tar1090/data at /run/adsbexchange and (optional but highly recommended) the bash script that makes history files from a configurable path (/run/adsbexchange) and puts them in /run/tar1090 ... then you also need http config pointing /tar1090/chunks at /run/tar1090.
The github repo has http configuration templates for nginx and lighttpd.
nginx is highly recommended, once you use it you won't want to go back!

Anyhow i wouldn't want to make a PR for this stuff as you know better how you want it integrated.
There is also a tar1090 docker container by mikenye but it runs its own readsb .. you wouldn't need to do that but you certainly could easy enough if you want it independent of the adsbexchange feed part.
 https://github.com/mikenye/docker-tar1090/

**Comment by ketilmo** [comment]
Awesome @wiedehopf! I have tested the changes, and they appear to work well. I'm going ahead and merging now. 

Thanks for the suggestion to add tar1090. I've added it to the roadmap (#41), along with #24.

Speaking of readsb – would you recommend replacing dump1090 with it?

**Comment by wiedehopf** [comment]
Dump1090-fa is well maintained by obj / mutability.
readsb is a fork of it originally started by Mictronics.
In turn i forked that and he stopped dev on it or rather changed to developing a version that only produces protobuf and no json.

My fork is the backend for https://globe.adsbexchange.com/ so ... it has a lot of stuff that's not needed for a home receiver.
Really it doesn't matter much which program talks to the SDR.
The only gripe i have with dump1090-fa is the heavy FA branding in the webinterface ... the reason why i started on tar1090.
But i've removed some SDR support like bladeRF from readsb because that's not my aim with the fork and i wanted to reduce repository size.
dump1090-fa now also has the quick gain adjustment while running, readsb lacks that and i have no plans for it at the moment.

readsb has a nice feature some people might like, persistent replay going back as far as you have disk space: https://globe.adsbexchange.com/?replay
It kinda requires --globe-index --globe-history to be enabled as well to get fine grained traces when you select an aircraft in the replay.
Or i suppose you could increase the replay granularity but it would still lack the finer data.
The traces need some better way to search them but someone could always implement some database with an interface to catalogue the traces and make them searchable.

Don't really have an opinion on it, it's a matter of taste ...

**Comment by ketilmo** [comment]
Thanks for clarifying, @wiedehopf! Sounds like we can stay on dump1090 for the time being, then. Since readsb is implemented in the adsb-exchange container already, we can use that for the tar1090 interface as you point out.

**Comment by ketilmo** [comment]
And thanks for your additions to the setup, @wiedehopf! It's highly appreciated! :)

**Pull request merged**
