### PR TITLE
Add option to reboot device

### PR DESCRIPTION
**Pull request by Teko012**
From time to time, I experience an issue, where the device looses connection to the hardware, and can't find it anymore. This adds an option to be able to automatically reboot the device if it can't find any hardware.

### CODE REVIEW

**Comment by Teko012** [comment]
@ketilmo If you have some time to check this as well if I haven't broken anything, that would be great :)

**Comment by ketilmo** [comment]
Hi @Teko012,

Thanks for another excellent suggestion. I've experienced the same problem a few times, with the USB dongle needing a complete reboot after a crash/exit to be operational again. Implementing a way to handle this automatically when it happens is a good idea. Your code looks good, but I have a few comments/points for discussion:

- **Making the variable naming generic:** For instance, a common variable across the services with the name `REBOOT_DEVICE_ON_SERVICE_EXIT` or similar would be passed to the respective service as a _service_ variable. This would make it easier to scale in the future and maintain, with less hardcoding per service.
-  **Rebooting the device using the balena API:** Inspired by your PR #123, using the API would ensure a graceful shutdown across the full range of balena's supported hardware devices. See the balena API docs here: https://docs.balena.io/reference/supervisor/supervisor-api/#post-v1reboot (using the --force option might be necessary?)
- **Writing a line to the console when functionality is active:** To remind the user that the option is turned on, write something like "Device reboot on service exit is enabled" as part of the variable validation at the start.sh.
- **Add a short description to the docs:** Under Advanced Configuration, with the heading "Automatic Device Reboot" or similar: https://github.com/ketilmo/balena-ads-b?tab=readme-ov-file#part-13--advanced-configuration

What do you think?

**Comment by Teko012** [comment]
> Hi @Teko012,
> 
> Thanks for another excellent suggestion. I've experienced the same problem a few times, with the USB dongle needing a complete reboot after a crash/exit to be operational again. Implementing a way to handle this automatically when it happens is a good idea. Your code looks good, but I have a few comments/points for discussion:
> 
> * **Making the variable naming generic:** For instance, a common variable across the services with the name `REBOOT_DEVICE_ON_SERVICE_EXIT` or similar would be passed to the respective service as a _service_ variable. This would make it easier to scale in the future and maintain, with less hardcoding per service.
> * **Rebooting the device using the balena API:** Inspired by your PR [Stop disabled services #123](https://github.com/ketilmo/balena-ads-b/pull/123), using the API would ensure a graceful shutdown across the full range of balena's supported hardware devices. See the balena API docs here: https://docs.balena.io/reference/supervisor/supervisor-api/#post-v1reboot (using the --force option might be necessary?)
> * **Writing a line to the console when functionality is active:** To remind the user that the option is turned on, write something like "Device reboot on service exit is enabled" as part of the variable validation at the start.sh.
> * **Add a short description to the docs:** Under Advanced Configuration, with the heading "Automatic Device Reboot" or similar: https://github.com/ketilmo/balena-ads-b?tab=readme-ov-file#part-13--advanced-configuration
> 
> What do you think?

Hey @ketilmo good feedback, I have updated the the PR :)

**Comment by ketilmo** [comment]
@Teko012 I just tested this functionality, and it works like a charm. One again: Great work, and thanks! I'm merging the PR now.

**Pull request merged**
