### PR TITLE
wifi-connect: temporary fix

### PR DESCRIPTION
**Pull request by shawaj**
Temporary fix for https://github.com/ketilmo/balena-ads-b/issues/142
- pull in required changes from https://github.com/balena-os/wifi-connect/pull/566
- increase timeout from 120 seconds to 180 seconds
- Fixes the error `D-Bus error: In D-Bus address, character '"' should have been escaped` due to incorrect env variable

Closes: https://github.com/ketilmo/balena-ads-b/issues/142

### CODE REVIEW

**Comment by shawaj** [comment]
Just need to test this works as expected

**Comment by shawaj** [comment]
All tested and works perfectly on my local device. Just used it to configure wifi.

**Comment by shawaj** [comment]
Added a fix for this, when trying to run directly from terminal...

Screenshot_20240824_005426_Chrome

**Comment by ketilmo** [comment]
Awesome @shawaj! Thank you for identifying and resolving this issue with this temporary fix. LGTM.

**Comment by shawaj** [comment]
Hopefully the fix gets merged upstream soon 🤞

**Comment by ketilmo** [comment]
Fingers crossed for that, @shawaj!

**Pull request merged**
