### PR TITLE
Test deploy action

### PR DESCRIPTION
**Pull request by maggie0002**

### CODE REVIEW

**Comment by maggie0002** [comment]
@ketilmo, looks like it is running here: https://github.com/ketilmo/balena-ads-b/actions

**Comment by maggie0002** [comment]
I may have given the wrong info though, looks like `BALENA_API_KEY` is actually supposed to be `BALENA_TOKEN`. Sorry about that.

**Comment by maggie0002** [comment]
Actually, that may just be because I raised this PR and third-party contributions may not be able to access things stored in secrets.

**Comment by ketilmo** [comment]
@maggie0002 Thanks for verifying. Would you like me to add the key to BALENA_TOKEN, or is BALENA_API_KEY the correct place to store it?

**Comment by maggie0002** [comment]
BALENA_API_KEY

https://github.com/ketilmo/balena-ads-b/blob/cbe9e79053ead4ab3f60a0800e9c52c85b63b793/.github/workflows/deploy-to-balena.yml#L34

**Comment by ketilmo** [comment]
I got it, thanks! Is there a way I can setup the rights for this to execute?

**Comment by maggie0002** [comment]
This was just a test PR. I added a random string at the top of the README that wasn't intended to be merged.

**Comment by maggie0002** [comment]
> I got it, thanks! Is there a way I can setup the rights for this to execute?

I think GitHub has some permissions that allow you to grant use of secrets on a case by case basis, you can select authorise when someone raises a PR. I can't find the docs for it though.

**Comment by ketilmo** [comment]
> This was just a test PR. I added a random string at the top of the README that wasn't intended to be merged.

My mistake. I have reverted the changes. I will see if I can find a way to grant access.

**Comment by ketilmo** [comment]
I raised a pull request myself, and the process appears to work now. That said, the repo is deployed upon the pull request being raised rather than approved. Is this the expected behavior? Is there a way to automatically push GitHub released to BalenaHub after a release?

**Comment by maggie0002** [comment]
> I raised a pull request myself, and the process appears to work now. That said, the repo is deployed upon the pull request being raised rather than approved. Is this the expected behavior? Is there a way to automatically push GitHub released to BalenaHub after a release?

When the PR is raised it deploys to the Cloud, but if you look in the dashboard under `releases` you will see it is not finalised (finalised will = false). This. means it is not available yet to users. When the PR is merged, the action is triggered again, and rather than build again it will just mark that release as finalised and make it available to your users.

**Comment by ketilmo** [comment]
Sounds good, @maggie0002! Thanks for your assistance. Let me know if I need to change anything in the future.

**Comment by maggie0002** [comment]
> Sounds good, @maggie0002! Thanks for your assistance. Let me know if I need to change anything in the future.

I think it should now sync the README, but it works when things are changed via PR rather than through direct pushes to the main branch. 

It seems your flows involve pushing directly to main. Perhaps we could change this section to push automatically on those too?

https://github.com/ketilmo/balena-ads-b/blob/a35362f9166a87372824d61dab2503704c93158a/.github/workflows/deploy-to-balena.yml#L3-L10

```diff
on:
+  push:
+    branches:
+      - main
+      - master
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - main
      - master
    paths-ignore:
      - 'docs/**'
```

**Comment by ketilmo** [comment]
That's a correct observation. The majority of changes are committed directly to the master branch. I have implemented the suggestions. Let's see if it works. PS! I see that the docs are excluded from the build. This would potentially leave out updated documentation/images, but that might be all right?

**Comment by maggie0002** [comment]
As long as those docs aren't used by your app (as in not used inside the container) then it shouldn't matter. It just avoids triggering a build when something changes in that folder. It seems like all your README links to full URLs, I don't think it will be an issue. 

Great spot though. This is giving me great food for thought on the balena deploy action.

**Comment by ketilmo** [comment]
Hi @maggie0002,

`ketil/balena-ads-b` is the name of the balena app in the balena Hub universe, but the GitHub name is ketilmo/balena-ads-b.   Is this correct, then? I committed the last change (which was successfully triggered and ran) through the GitHub web UI, so local changes should not affect anything here.

**Comment by maggie0002** [comment]
Is it perhaps marked as finalised = false in the Cloud panel?

**Comment by ketilmo** [comment]
The latest build has a status of finalised = true, but it is not flagged as release track default.

**Comment by maggie0002** [comment]
> The latest build has a status of finalised = true, but it is not flagged as release track default.

That would explain it, so it is just a matter of setting the release to the new pushed content. 

Thanks for going through this with me, has been really great for the project, and really helpful for me to understand some of these different workflows

**Comment by ketilmo** [comment]
Thank you for all your efforts in getting this up and running, @maggie0002! I did a commit earlier today, and everything appeared to work smoothly.

**Comment by maggie0002** [comment]
Fantastic! Looks like there is now a nice rich page on the Hub too, hopefully it will be easier for people to find the project 😄 

https://hub.balena.io/organizations/ketil/apps/balena-ads-b

**Comment by ketilmo** [comment]
Sounds great, @maggie0002! A practical question, since the balena hub seems to have undergone massive development lately: People who have deployed the balena-ads-b application to their own fleet will they get updates automatically rolled out? Or do they have to re-deploy the app with the blue Deploy to balena-button, or similar flows?

**Comment by maggie0002** [comment]
If a user deploys an application to their own fleet then there aren't automatic updates (in the past or in the present). Apps have always been the ability to create your own version (think of it like a GitHub fork, you only get updates when you take action to bring them across), whereas fleets you hook in to a users GitHub and get the updates automatically.

**Comment by ketilmo** [comment]
That makes sense, @maggie0002! Thanks for clarifying.

**Pull request merged**
