### PR TITLE
Update supported devices, refactor README

### PR DESCRIPTION
**Pull request by Teko012**
- Update supported devices
- Refactor README

### CODE REVIEW

**Comment by ketilmo** [comment]
Looks good to me, @Teko012! Thank you so much for your improvements. 🙌🏻

**Comment by shawaj** [comment]
Not sure if it's just for me but the updated SVG header has weird formatting:

Screenshot_20240705_221335_Chrome

Compared to the previous PNG...
Screenshot_20240705_221457_Chrome

**Comment by shawaj** [comment]
Just FYI ^^ @Teko012 @ketilmo

**Comment by Teko012** [comment]
@shawaj Hm, interesting. Which browser/version are you on?

**Comment by Teko012** [comment]
Also, does [this version](https://github.com/ketilmo/balena-ads-b/blob/22606f094edc41e2699b27a72ba638ddf0b0045d/docs/images/header.svg) shows properly?

**Comment by shawaj** [comment]
I'm viewing on Android / Chrome on an S24 Ultra.

It shows the same in chrome, in the native viewer and also if I upload the SVG itself to this web viewer. 

https://www.rapidtables.com/web/tools/svg-viewer-editor.html

So maybe it's just the file?

Using this SVG...

<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg width="100%" height="100%" viewBox="0 0 284 32" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xml:space="preserve" xmlns:serif="http://www.serif.com/" style="fill-rule:evenodd;clip-rule:evenodd;stroke-linejoin:round;stroke-miterlimit:2;">
    <g transform="matrix(1,0,0,1,-7.33893,-13.7342)">
        <path d="M46.052,23.23L48.678,23.23L48.678,27.547L48.718,27.547C49.012,27.158 49.401,26.85 49.846,26.652C50.32,26.451 50.816,26.308 51.324,26.224C51.441,26.224 51.596,26.184 51.724,26.184L52.074,26.184C53.549,26.139 54.976,26.718 56.002,27.779C56.974,28.747 57.52,30.063 57.519,31.435C57.525,31.643 57.512,31.851 57.479,32.057C57.446,32.281 57.393,32.502 57.323,32.718C57.209,33.147 57.052,33.564 56.856,33.963C56.665,34.349 56.416,34.704 56.116,35.013C55.628,35.557 55.014,35.971 54.327,36.219C53.634,36.495 52.895,36.64 52.149,36.647C51.442,36.66 50.74,36.528 50.087,36.257C49.453,35.994 48.901,35.563 48.492,35.012L48.452,35.012L48.452,36.334L46.052,36.334L46.052,23.23ZM49.495,29.337C48.868,29.817 48.507,30.569 48.523,31.36C48.511,32.178 48.823,32.965 49.418,33.538C50.056,34.144 50.912,34.466 51.791,34.432C52.629,34.473 53.447,34.162 54.047,33.576C54.623,33.034 54.936,32.267 54.903,31.476C54.921,30.688 54.611,29.926 54.047,29.376C53.447,28.79 52.629,28.479 51.791,28.52C50.951,28.505 50.137,28.795 49.496,29.337L49.495,29.337ZM69.993,36.417L67.58,36.417L67.58,35.095L67.54,35.095C67.203,35.545 66.763,35.895 66.256,36.145C65.733,36.419 65.168,36.603 64.584,36.69C64.467,36.69 64.35,36.73 64.234,36.73L63.884,36.73C63.111,36.738 62.344,36.593 61.628,36.302C60.977,36.029 60.393,35.617 59.916,35.096C59.477,34.622 59.134,34.067 58.905,33.462C58.673,32.84 58.555,32.181 58.555,31.517C58.554,30.869 58.659,30.225 58.866,29.611C59.113,29.007 59.469,28.453 59.916,27.978C60.424,27.421 61.048,26.983 61.744,26.694C62.448,26.407 63.201,26.261 63.961,26.266C64.67,26.265 65.373,26.411 66.023,26.694C66.659,26.972 67.21,27.416 67.618,27.978L67.618,26.578L70.03,26.578L70.03,36.418L69.993,36.417ZM67.543,31.437C67.569,30.659 67.256,29.906 66.687,29.375C66.092,28.775 65.267,28.475 64.431,28.558C63.459,28.558 62.681,28.83 62.098,29.414C61.5,29.977 61.173,30.771 61.203,31.592C61.19,32.372 61.533,33.118 62.137,33.615C62.763,34.155 63.567,34.447 64.393,34.432C65.243,34.473 66.073,34.163 66.688,33.576C67.25,33.007 67.558,32.235 67.544,31.436L67.543,31.437ZM71.938,23.23L74.544,23.23L74.544,36.416L71.938,36.416L71.938,23.23ZM78.938,32.526C79.124,33.107 79.51,33.603 80.027,33.926C80.56,34.268 81.183,34.444 81.817,34.432C82.294,34.437 82.768,34.358 83.217,34.199C83.602,34.081 83.95,33.867 84.217,33.577L87.095,33.577C86.795,34.472 86.123,35.211 85.111,35.833C84.146,36.446 83.026,36.77 81.883,36.767C80.39,36.8 78.941,36.256 77.838,35.25C76.762,34.344 76.148,33.001 76.166,31.594C76.146,30.153 76.757,28.774 77.838,27.821C78.942,26.786 80.41,26.227 81.922,26.265C83.399,26.228 84.831,26.79 85.889,27.821C86.978,28.871 87.523,30.077 87.523,31.438C87.529,31.595 87.516,31.752 87.483,31.905C87.443,32.06 87.443,32.205 87.405,32.333C87.405,32.373 87.365,32.411 87.365,32.45L87.365,32.567L78.925,32.567L78.938,32.526ZM84.888,30.426C84.696,29.846 84.293,29.361 83.76,29.064C83.213,28.722 82.577,28.546 81.932,28.559L81.776,28.559C81.158,28.603 80.559,28.79 80.026,29.104C79.514,29.399 79.123,29.868 78.926,30.426L84.888,30.426ZM89.17,26.526L91.617,26.526L91.617,27.42L91.657,27.42C91.977,27.051 92.376,26.758 92.824,26.564C93.322,26.37 93.847,26.252 94.38,26.214L94.924,26.214C95.449,26.251 95.963,26.383 96.441,26.603C96.919,26.805 97.355,27.095 97.725,27.459C97.765,27.499 97.842,27.537 97.88,27.576C97.928,27.62 97.968,27.673 97.997,27.731C98.4,28.22 98.657,28.814 98.736,29.443C98.815,30.062 98.854,30.686 98.853,31.31L98.853,36.405L96.247,36.405L96.247,31.27C96.253,31.101 96.24,30.931 96.208,30.765C96.179,30.514 96.127,30.267 96.053,30.026C95.989,29.789 95.883,29.566 95.753,29.366C95.575,29.114 95.333,28.913 95.053,28.783C94.778,28.634 94.472,28.554 94.159,28.55L93.759,28.55C93.447,28.586 93.144,28.679 92.864,28.822C92.601,28.962 92.375,29.162 92.204,29.405C92.077,29.614 91.973,29.835 91.893,30.066C91.816,30.318 91.777,30.58 91.776,30.844L91.776,36.406L89.17,36.406L89.17,26.526ZM111.959,36.406L109.547,36.406L109.547,35.084L109.507,35.084C109.17,35.534 108.73,35.884 108.223,36.134C107.7,36.408 107.135,36.592 106.551,36.679C106.434,36.679 106.318,36.719 106.201,36.719L105.851,36.719C105.078,36.727 104.311,36.582 103.595,36.291C102.944,36.018 102.36,35.606 101.884,35.085C101.445,34.611 101.102,34.056 100.873,33.451C100.641,32.829 100.523,32.17 100.523,31.506C100.522,30.858 100.627,30.214 100.834,29.6C101.081,28.996 101.437,28.442 101.884,27.967C102.392,27.41 103.016,26.972 103.712,26.683C104.416,26.396 105.169,26.25 105.929,26.255C106.638,26.254 107.341,26.4 107.991,26.683C108.627,26.961 109.178,27.405 109.586,27.967L109.586,26.567L112,26.567L112,36.407L111.959,36.406ZM109.459,31.426C109.485,30.648 109.172,29.895 108.603,29.364C108.008,28.764 107.183,28.464 106.347,28.547C105.375,28.547 104.597,28.819 104.014,29.403C103.416,29.966 103.089,30.76 103.119,31.581C103.106,32.361 103.449,33.107 104.053,33.604C104.679,34.144 105.483,34.436 106.309,34.421C107.159,34.462 107.989,34.152 108.604,33.565C109.181,33.007 109.504,32.228 109.46,31.425L109.459,31.426Z" style="fill:rgb(42,80,111);fill-rule:nonzero;"/>
    </g>
    <g transform="matrix(0.0641971,0,0,0.0641971,-0.364704,-0.192784)">
        <path d="M252.209,3.003C116.055,3.003 5.681,113.378 5.681,249.531C5.681,385.685 116.056,496.059 252.209,496.059C388.363,496.059 498.738,385.685 498.738,249.531C498.738,113.378 388.364,3.003 252.209,3.003ZM407.887,405.21C387.659,425.438 364.112,441.315 337.898,452.403C310.773,463.876 281.942,469.694 252.209,469.694C222.476,469.694 193.646,463.876 166.521,452.403C140.307,441.315 116.759,425.437 96.531,405.21C76.303,384.981 60.425,361.435 49.338,335.221C37.865,308.095 32.047,279.265 32.047,249.532C32.047,219.799 37.864,190.969 49.338,163.844C60.425,137.63 76.304,114.082 96.531,93.855C116.759,73.627 140.307,57.749 166.521,46.662C193.646,35.188 222.477,29.371 252.209,29.371C281.942,29.371 310.772,35.188 337.898,46.662C364.112,57.749 387.66,73.628 407.887,93.855C428.115,114.083 443.993,137.63 455.081,163.844C466.554,190.969 472.372,219.799 472.372,249.532C472.372,279.265 466.555,308.095 455.081,335.221C443.994,361.435 428.115,384.981 407.887,405.21Z" style="fill:rgb(223,175,55);fill-rule:nonzero;"/>
    </g>
    <g transform="matrix(0.0641971,0,0,0.0641971,-0.364704,-0.192784)">
        <path d="M399.182,305.834L410.019,255.334C410.62,251.871 406.47,249.544 403.938,251.98C403.919,251.999 403.848,252.069 403.829,252.087L377.754,284.708L351.406,261.611C350.908,261.157 350.661,260.491 350.743,259.822L352.347,246.796C352.476,245.717 351.17,244.871 350.429,245.608C350.423,245.614 350.402,245.635 350.397,245.64L344.009,255.117C342.894,256.771 341.465,258.19 339.803,259.292L330.38,265.543C330.374,265.548 330.369,265.554 330.363,265.56C329.622,266.296 330.427,267.64 331.508,267.517L344.724,265.994C345.391,265.918 346.055,266.168 346.504,266.668L369.38,293.504L336.5,319.031C336.481,319.051 336.463,319.068 336.445,319.088C333.993,321.607 336.262,325.803 339.728,325.223L390.49,314.656L407.088,331.895C409.85,334.672 413.976,335.09 416.755,332.329C419.533,329.566 419.139,325.437 416.377,322.659L399.182,305.834Z" style="fill:rgb(42,80,111);fill-rule:nonzero;"/>
    </g>
    <g transform="matrix(0.0641971,0,0,0.0641971,-0.364704,-0.192784)">
        <path d="M293.303,364.935L300.488,343.542C301.608,340.022 300.159,336.39 296.639,335.27C293.118,334.151 289.838,336.279 288.718,339.798L282.141,361.509L235.187,374.448C232.03,375.455 231.891,379.938 235.032,380.995C235.055,381.003 235.146,381.032 235.169,381.04L273.811,388.633L265.975,420.731C265.812,421.345 265.363,421.841 264.768,422.064L253.175,426.399C252.216,426.761 252.078,428.222 253.017,428.521C253.024,428.523 253.051,428.531 253.058,428.534L263.766,429.747C265.635,429.959 267.444,430.536 269.09,431.445L278.423,436.602C278.43,436.604 278.437,436.607 278.444,436.609C279.382,436.908 280.155,435.648 279.582,434.798L272.55,424.409C272.195,423.885 272.115,423.221 272.337,422.627L284.813,391.804L320.488,408.179C320.511,408.186 320.535,408.193 320.558,408.2C323.732,409.153 326.254,405.427 324.258,402.781L293.303,364.935Z" style="fill:rgb(42,80,111);fill-rule:nonzero;"/>
    </g>
    <g transform="matrix(0.0641971,0,0,0.0641971,-0.364704,-0.192784)">
        <path d="M140.428,262.553C140.403,262.549 140.307,262.533 140.282,262.53L100.055,260.825L103.016,227.174C103.085,226.528 103.463,225.957 104.029,225.64L115.076,219.468C115.989,218.953 115.903,217.456 114.908,217.299C114.901,217.298 114.872,217.293 114.865,217.292L104.933,217.679C119.59,149.843 180.052,98.855 252.209,98.855C290.645,98.855 327.844,113.762 355.684,140.026L308.561,183.042C292.922,169.78 273.016,162.372 252.208,162.372C204.147,162.372 165.046,201.473 165.046,249.533C165.046,297.595 204.147,336.695 252.208,336.695C254.969,336.695 257.208,334.457 257.208,331.695C257.208,328.933 254.969,326.695 252.208,326.695C209.661,326.695 175.046,292.08 175.046,249.533C175.046,206.986 209.661,172.372 252.208,172.372C270.191,172.372 287.413,178.627 301.104,189.849L261.489,226.011C258.615,224.876 255.486,224.245 252.208,224.245C238.242,224.245 226.92,235.567 226.92,249.533C226.92,263.5 238.242,274.821 252.208,274.821C266.175,274.821 277.497,263.5 277.497,249.533C277.497,246.091 276.807,242.81 275.56,239.819L387.801,137.361C391.8,133.712 392.085,127.454 388.435,123.456C384.786,119.458 378.528,119.173 374.53,122.822L363.091,133.264C333.346,104.942 293.445,88.855 252.209,88.855C175.218,88.855 110.717,143.292 95.134,215.692L87.983,213.056C87.976,213.055 87.968,213.054 87.961,213.053C86.966,212.896 86.38,214.287 87.09,215.058L95.802,224.471C96.242,224.948 96.424,225.606 96.292,226.241L88.445,259.321L49.86,248.28C49.835,248.276 49.81,248.272 49.785,248.269C46.43,247.796 44.456,251.952 46.882,254.317L84.015,287.788L80.057,310.517C79.469,314.248 81.495,317.696 85.225,318.284C88.955,318.872 91.943,316.215 92.532,312.483L95.826,289.524L141.283,269.193C144.319,267.688 143.766,263.135 140.428,262.553Z" style="fill:rgb(42,80,111);fill-rule:nonzero;"/>
    </g>
    <g transform="matrix(0.0641971,0,0,0.0641971,-0.364704,-0.192784)">
        <path d="M113.494,313.633L110.817,329.877C137.524,375.52 186.112,406.996 242.406,409.491L245.584,399.603C187.117,398.062 137.139,363.202 113.494,313.633Z" style="fill:rgb(42,80,111);fill-rule:nonzero;"/>
    </g>
    <g transform="matrix(1.17269,0,0,1.17269,80.2179,-39.0391)">
        <g transform="matrix(1,0,0,1,25.267,52.55)">
            <text x="0px" y="0px" style="font-family:'ArialRoundedMTBold', 'Arial Rounded MT Bold', sans-serif;font-size:14.667px;fill:rgb(223,175,55);">ADS-B F</text>
        </g>
        <g transform="matrix(1,0,0,1,84.22,52.55)">
            <text x="0px" y="0px" style="font-family:'ArialRoundedMTBold', 'Arial Rounded MT Bold', sans-serif;font-size:14.667px;fill:rgb(223,175,55);">light T</text>
        </g>
        <g transform="matrix(1,0,0,1,127.662,52.55)">
            <text x="0px" y="0px" style="font-family:'ArialRoundedMTBold', 'Arial Rounded MT Bold', sans-serif;font-size:14.667px;fill:rgb(223,175,55);">r<tspan x="6.059px 14.774px 22.932px 30.781px 39.496px " y="0px 0px 0px 0px 0px ">acker</tspan></text>
        </g>
    </g>
</svg>

**Comment by shawaj** [comment]
Screenshots
Screenshot_20240705_231621_Chrome
Screenshot_20240705_231634_Chrome

**Comment by Teko012** [comment]
@shawaj How does this look? header_v2

**Comment by shawaj** [comment]
Perfect 👍

**Comment by Teko012** [comment]
Great, thanks for reporting! I will update the logo on my other open PR.

**Pull request merged**
